# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeFlipper < Formula
  desc "Flip between multiple Claude Code accounts without logging out and back in."
  homepage "https://github.com/thecoderbuddy/claude-flipper"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v1.0.0/claude-flipper_darwin_amd64.tar.gz"
      sha256 "ef418e83a8b2312d50139dcb793c78d16309de4f27d93d0f5159db6c1f01d25d"

      define_method(:install) do
        bin.install "flipper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v1.0.0/claude-flipper_darwin_arm64.tar.gz"
      sha256 "7b6a673ace844b375c8a252dad936cdaf18dd732f22904d6fcec99a69fe66899"

      define_method(:install) do
        bin.install "flipper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v1.0.0/claude-flipper_linux_amd64.tar.gz"
      sha256 "8a3e6ddff62d187f1c4f872ebb684b30fc1829b2a7921b6364b67dff6959c11e"
      define_method(:install) do
        bin.install "flipper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v1.0.0/claude-flipper_linux_arm64.tar.gz"
      sha256 "84649c696f4e8a4445e3ca70b5c5f40767dbf7668c6a100289d050ddd64cfa77"
      define_method(:install) do
        bin.install "flipper"
      end
    end
  end

  test do
    system "#{bin}/flipper", "--help"
  end
end
