# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeFlipper < Formula
  desc "Flip between multiple Claude Code accounts without logging out and back in."
  homepage "https://github.com/thecoderbuddy/claude-flipper"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v0.7.0/claude-flipper_darwin_amd64.tar.gz"
      sha256 "ccc80a3fa53df74e4c7cc0a68d293882fbe34ad441fabacecf9c7cc11f2ad16f"

      define_method(:install) do
        bin.install "flipper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v0.7.0/claude-flipper_darwin_arm64.tar.gz"
      sha256 "a3f3c3ad727208cd520030218de024c9e9cabb1ec6a052e0462ef8dea88400da"

      define_method(:install) do
        bin.install "flipper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v0.7.0/claude-flipper_linux_amd64.tar.gz"
      sha256 "16f60437bd3f6409a62666e4dc46bf40c1856ad98d11c8db2656d14356ff0d3c"
      define_method(:install) do
        bin.install "flipper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thecoderbuddy/claude-flipper/releases/download/v0.7.0/claude-flipper_linux_arm64.tar.gz"
      sha256 "29255fcc261b1956b6ab52937e14b7bdb4ab976621b4760c30a8057fcd34e20a"
      define_method(:install) do
        bin.install "flipper"
      end
    end
  end

  test do
    system "#{bin}/flipper", "--help"
  end
end
